name: Pylint

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    #- name: Analysing the code with pylint
    #  run: |
    #    pylint `ls -R|grep .py$|xargs`
    - name: Unit tests
      run: |
        python -m venv .linux_env
        source ./.linux_env/bin/activate
        pip install -r requirements.txt
        python -m unittest discover -v -s  "tests/" -p "*_test.py"
